version: '3'

services:
  neo4j:
    image: neo4j:4.2.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
  app:
    build: .
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    environment:
      - TEMPLATES_LOCATION=/app/frontend/templates
      - DB_HOSTNAME=neo4j
